### ISSUE TITLE
Auto index broken with Rails 5

### ISSUE THREAD

**Issue by owenbendavies** [SchemaPlus/schema_auto_foreign_keys#2]
Since upgrading to Rails 5, the auto index function of schema_auto_foreign_keys has stopped working.

Good:
rails (4.2.7.1)
schema_plus_core (1.0.2)

Bad:
rails (5.0.0.1)
schema_plus_core (2.0.1)

Having dug into the code previously in https://github.com/SchemaPlus/schema_auto_foreign_keys/blob/master/lib/schema_auto_foreign_keys/middleware/migration.rb#L54 `env.options` did not contain the index key unless set, but now has `{index: false}`. I'm not quite sure how to fix this, as it still needs the way for people to explicitly not set an index.

Thanks,
Owen

**Comment by boazy** [comment]
Can you post a schema which reproduces this issue? I don't see this behavior on Rails 5, so there's either something strange going on on your side, or I didn't really understand your issue.
The specs explicitly test that an index is created if not explicitly disabled:
https://github.com/SchemaPlus/schema_auto_foreign_keys/blob/master/spec/migration_spec.rb#L128

I've also looked at the generated schema.rb in one of my projects, and it contains the indexes.

**Comment by owenbendavies** [comment]
So I have dug more and found I am currently using the following format in my migrations:

```
table.belongs_to :site, null: false
```

if I change it to:

```
table.integer :site_id, null: false
```

it works. I assume this is a change in the Rails code so will have a dig.

**Comment by boazy** [comment]
Looks like it fails when using `belongs_to`, although it's supposed to work.
I thought it's being tested here:
https://github.com/SchemaPlus/schema_auto_foreign_keys/blob/master/spec/migration_spec.rb#L97

@ronen do you have any idea why this test wouldn't detect the missing index? Or is it just a dumper issue and the index actually gets created?

**Comment by ronen** [comment]
@boazy Yeah, in the test suite, at https://github.com/SchemaPlus/schema_auto_foreign_keys/blob/master/spec/migration_spec.rb#L97
it definitely creates the index.  I doublechecked the log that the index is really being created and that the matcher isn't reporting a false positive.  (To that end I just pushed 590d004 because when I was poking around a bit I did actually see some false positives!)

@obduk You say that you're seeing
>  in https://github.com/SchemaPlus/schema_auto_foreign_keys/blob/master/lib/schema_auto_foreign_keys/middleware/migration.rb#L54 env.options did not contain the index key unless set, but now has {index: false}

Since that's clearly not happening in the test suite, do you have something else in the mix that could be interacting with the env options?  (Possibly even another schema_plus gem?)

Thanks for digging... if nothing else if you can can point @boazy or me at a failing case we could look into it.

**Comment by owenbendavies** [comment]
So I can see why it is doing it in the ActiveRecord code:

```
activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb

      def references(*args)
        options = args.extract_options!
        polymorphic = options.delete(:polymorphic)
        index_options = options.delete(:index)
        foreign_key_options = options.delete(:foreign_key)
        type = options.delete(:type) || :integer
```

```
activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb

   class ReferenceDefinition # :nodoc:
      def initialize(
        name,
        polymorphic: false,
        index: true,
        foreign_key: false,
        type: :integer,
        **options
      )
        @name = name
        @polymorphic = polymorphic
        @index = index
        @foreign_key = foreign_key
        @type = type
        @options = options
```

So before index was nil, now it is false. However I can't see why this would be different in this them tests. I have managed to re-produce it on my home test project:

https://github.com/obduk/cms/pull/679
https://travis-ci.org/obduk/cms/builds/184075380

I will try and dig further, and try and create a failing test case.

**Comment by owenbendavies** [comment]
I have discovered the issue. In migrations on rails 5, it adds the version to any new migrations

```
class CreateUsers < ActiveRecord::Migration[5.0]
```

However existing migrations are left the same. After adding this to my existing migrations it started working.

So:
Rails 4 = works
Rails 5 with old migrations = broken
Rails 5 with Rails 5 migrations = works

**Comment by owenbendavies** [comment]
See this blog for more information http://blog.bigbinary.com/2016/03/01/migrations-are-versioned-in-rails-5.html

**Comment by ronen** [comment]
@obduk oh, that's subtle!  Nice sleuthing.

But the question then is whether we can compensate for that somehow in this gem.  Ideally Rails 5 with old migrations *should* still work.  Or at worst print a warning/deprecation that auto indexes don't work with that combo and suggest upgrading to Rails 5 migrations or manually creating the index.

Having been through the code, do you think you could come up with the appropriate fix?

**Comment by owenbendavies** [comment]
I think it will be hard to fix without submitting a fix to Rails. Essentially Rails 5 legacy migrations now set index to false whereas before it was set to nil. This means we can't detect if the user or Rails set it as false.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/compatibility.rb#L57

It could be possible to add a warning / error for this case similar to this one

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/compatibility.rb#L136

I probably won't have time to do this until the new year, but will let you know if I do start on it.
